services:
  db:
    image: postgres:15-alpine
    container_name: help-desk-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helpdesk
    ports:
      - "51213:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d helpdesk"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: help-desk-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@helpdesk.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
     - db

  app:
    build: .
    container_name: help-desk-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/helpdesk?schema=public"
      PORT: 3000
    depends_on:
      - db

volumes:
    postgres_data: